---
abstract: 'Perl extension for examining dependencies on modules'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Dependencies
no_index:
  directory:
    - t
    - inc
requires:
  Time::HiRes: 0
resources:
  repository: https://github.com/neilbowers/Devel-Dependencies
version: 1.02
